### ISSUE TITLE
No Code?

### ISSUE THREAD

**Issue by robmoffat** [finos-labs/fdc3-java-api#2]
Hi Guys,

Just wanted to check in on this - no code in the project yet.  I'd really like to present this to some people in the FDC3 community to let me know when it's coming.

thanks,
Rob

**Comment by garrettladley** [comment]
Hey @robmoffat, 

Sorry for the delay, the code is up now. We can't wait to hear your feedback!

**Comment by maoo** [comment]
Thanks @garrettladley , the repository looks really clean and well documented! The only suggestion I can make is to rename the main branch from `master` to `main`. I can do that, as soon as I get a confirmation from your end.

@TheJuanAndOnly99 - could you please run a quick review on your end?

@robmoffat will probably follow up with you to coordinate the collaboration with the rest of the FDC3 team and opportunities to demo/present at our events.

Exciting times, thanks everyone!

**Comment by garrettladley** [comment]
@maoo sounds good. You can go head and set default branch to `main` instead of `master`

**Comment by finos-admin** [comment]
All done, thanks! Closing issue.

**Comment by timjenkel** [comment]
@finos-admin @maoo 
You should also update https://github.com/finos-labs/project-blueprint to use main instead of master if you want future projects to use main

**Comment by maoo** [comment]
very good point @timjenkel ! just done, thank you! @TheJuanAndOnly99 - FYI
